In [3]:
t=int(input())
for i in range(t):
    l=[]
    n=int(input())
    l=list(map(int,input().split()))
print(l)
    

 1
 4
 1 2 3 4


[1, 2, 3, 4]


In [4]:
k=1000000000//2
print(k)

500000000


In [ ]:
import time
start = time.time()
for i in range(50000):
    print("",end="")
end = time.time()
print(f"Runtime of the program is {end - start}")

In [ ]:
from math import *
x=int(input())
k=sqrt(x)
for i in range(2,ceil(k)+1):
    print(i)
    

In [1]:
import time
for i in range(10):
    print('*',end="")
    time.sleep(0.3)

**********

In [9]:
for i in range(2,29):
    if (29%i==0):
        print(i)

In [4]:
import numpy as np
a=np.arange(20).reshape(4,5)
a=a*5+4
print(a)


[[ 4  9 14 19 24]
 [29 34 39 44 49]
 [54 59 64 69 74]
 [79 84 89 94 99]]


In [9]:
for i in range(1,100):
    if(i%7==0 and i%2!=0):
        print(i)

7
21
35
49
63
77
91


In [ ]:
def SieveOfEratosthenes(n): 
      
    # Create a boolean array "prime[0..n]" and initialize 
    #  all entries it as true. A value in prime[i] will 
    # finally be false if i is Not a prime, else true. 
    prime = [True for i in range(n+1)] 
    p = 2
    while (p * p <= n): 
          
        # If prime[p] is not changed, then it is a prime 
        if (prime[p] == True): 
              
            # Update all multiples of p 
            for i in range(p * p, n+1, p): 
                prime[i] = False
        p += 1
      
    # Print all prime numbers 
    for p in range(2, n): 
        if prime[p]: 
            print (p)
  
# driver program 
if __name__=='__main__': 
    n = 100
    print("Following are the prime numbers smaller than or equal to", n) 
    SieveOfEratosthenes(n) 

In [45]:
import math
import time
s=time.time()
l=[]
def factors(n):
    results = set()
    for i in range(1, int(math.sqrt(n)) + 1):
        if n % i == 0:
            results.add(i)
        results.add(int(n/i))
    return results
x=5
for i in range(1,100000):
    k=len(factors(i))
    if k==x:
        l.append(i)
print(l)
e=time.time()
print("Total time =",e-s)

[10, 14, 15, 17, 19, 23]
Total time = 17.841206550598145


In [39]:
import math
import time
start = time.time()

# function to count the divisors
def countDivisors(n):
    cnt = 0
    l=0
    for i in range(1,int(math.sqrt(n))+ 1):
        if (n % i == 0):
            # If divisors are equal,
            # count only one
            if (n / i == i):
                cnt = cnt + 1
            else:  # Otherwise count both
                cnt = cnt + 2
        # if cnt==x:
        #     print("#",i*i,"#")
        #     print(l)
        #     break
        # l=l+1
    return cnt

# Driver program to test above function
#x=int(input("Enter total factoes"))
print(" divisors =",countDivisors(1000000000))
end = time.time()
print(f"Runtime of the program is { end - start } ")


 divisors = 100
Runtime of the program is 0.012003421783447266 
